const Colors = {
  nav30: "#ECEEF0",
  grey600: "#AAAAAA",
  primary: "#366288",
  secondary: "#378176",
  white: "#FFFFFF",
  black: "#000000",
  grey: "#D6D6D6",
  red: "#E6767F",
};

const Typography = {
  fontFamily: {
    RobotoBlack: "Roboto-Black",
    RobotoBlackItalic: "Roboto-BlackItalic",
    RobotoBold: "Roboto-Bold",
    RobotoBoldItalic: "Roboto-BoldItalic",
    RobotoExtraBold: "Roboto-ExtraBold",
    RobotoExtraBoldItalic: "Roboto-ExtraBoldItalic",
    RobotoExtraLight: "Roboto-ExtraLight",
    RobotoExtraLightItalic: "Roboto-ExtraLightItalic",
    RobotoItalic: "Roboto-Italic",
    RobotoLight: "Roboto-Light",
    RobotoLightItalic: "Roboto-LightItalic",
    RobotoMedium: "Roboto-Medium",
    RobotoMediumItalic: "Roboto-MediumItalic",
    RobotoRegular: "Roboto-Regular",
    RobotoSemiBold: "Roboto-SemiBold",
    RobotoSemiBoldItalic: "Roboto-SemiBoldItalic",
    RobotoThin: "Roboto-Thin",
    RobotoThinItalic: "Roboto-ThinItalic",
    RobotoCondensedBlack: "Roboto_Condensed-Black",
    RobotoCondensedBlackItalic: "Roboto_Condensed-BlackItalic",
    RobotoCondensedBold: "Roboto_Condensed-Bold",
    RobotoCondensedBoldItalic: "Roboto_Condensed-BoldItalic",
    RobotoCondensedExtraBold: "Roboto_Condensed-ExtraBold",
    RobotoCondensedExtraBoldItalic: "Roboto_Condensed-ExtraBoldItalic",
    RobotoCondensedExtraLight: "Roboto_Condensed-ExtraLight",
    RobotoCondensedExtraLightItalic: "Roboto_Condensed-ExtraLightItalic",
    RobotoCondensedItalic: "Roboto_Condensed-Italic",
    RobotoCondensedLight: "Roboto_Condensed-Light",
    RobotoCondensedLightItalic: "Roboto_Condensed-LightItalic",
    RobotoCondensedMedium: "Roboto_Condensed-Medium",
    RobotoCondensedMediumItalic: "Roboto_Condensed-MediumItalic",
    RobotoCondensedRegular: "Roboto_Condensed-Regular",
    RobotoCondensedSemiBold: "Roboto_Condensed-SemiBold",
    RobotoCondensedSemiBoldItalic: "Roboto_Condensed-SemiBoldItalic",
    RobotoCondensedThin: "Roboto_Condensed-Thin",
    RobotoCondensedThinItalic: "Roboto_Condensed-ThinItalic",
    RobotoSemiCondensedBlack: "Roboto_SemiCondensed-Black",
    RobotoSemiCondensedBlackItalic: "Roboto_SemiCondensed-BlackItalic",
    RobotoSemiCondensedBold: "Roboto_SemiCondensed-Bold",
    RobotoSemiCondensedBoldItalic: "Roboto_SemiCondensed-BoldItalic",
    RobotoSemiCondensedExtraBold: "Roboto_SemiCondensed-ExtraBold",
    RobotoSemiCondensedExtraBoldItalic: "Roboto_SemiCondensed-ExtraBoldItalic",
    RobotoSemiCondensedExtraLight: "Roboto_SemiCondensed-ExtraLight",
    RobotoSemiCondensedExtraLightItalic:
      "Roboto_SemiCondensed-ExtraLightItalic",
    RobotoSemiCondensedItalic: "Roboto_SemiCondensed-Italic",
    RobotoSemiCondensedLight: "Roboto_SemiCondensed-Light",
    RobotoSemiCondensedLightItalic: "Roboto_SemiCondensed-LightItalic",
    RobotoSemiCondensedMedium: "Roboto_SemiCondensed-Medium",
    RobotoSemiCondensedMediumItalic: "Roboto_SemiCondensed-MediumItalic",
    RobotoSemiCondensedRegular: "Roboto_SemiCondensed-Regular",
    RobotoSemiCondensedSemiBold: "Roboto_SemiCondensed-SemiBold",
    RobotoSemiCondensedSemiBoldItalic: "Roboto_SemiCondensed-SemiBoldItalic",
    RobotoSemiCondensedThin: "Roboto_SemiCondensed-Thin",
    RobotoSemiCondensedThinItalic: "Roboto_SemiCondensed-ThinItalic",
  },
  fontSizes: {
    small: 12,
    medium: 14,
    large: 16,
    xLarge: 20,
    xxLarge: 24,
  },
  fontWeight: {
    small: 12,
    medium: 14,
    large: 16,
    xLarge: 20,
    xxLarge: 24,
  },
};

export { Colors, Typography };
